# Generated by Django 2.2.5 on 2019-09-18 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_num', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('education_degree', models.CharField(blank=True, choices=[('UnderGraduated', 'UnderGraduated'), ('Graduated', 'Graduated'), ('Master', 'Master'), ('PH.D', 'PH.D')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Manager Images/')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_num', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('address', models.CharField(max_length=300)),
                ('foods', models.ManyToManyField(related_name='stores', to='Food.Food')),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_manager', to='Store.Manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_num', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('education_degree', models.CharField(blank=True, choices=[('UnderGraduated', 'UnderGraduated'), ('Graduated', 'Graduated'), ('Master', 'Master'), ('PH', 'PH.D')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Employee Images/')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('position', models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Waitress', 'Waitress'), ('Head Chef', 'Head Chef'), ('Chef', 'Chef'), ('Accountant', 'Accountant')], max_length=50, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Store.Store')),
            ],
        ),
    ]
